### ISSUE TITLE
[BUG] web: iframe breaks UI for small screens.

### ISSUE THREAD

**Issue by Bitnagar** [heyxyz/hey#3947] opened 2023-11-03 04:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, the `iframe` for youtube videos breaks the UI layout on small screen devices as shown in the screenshot.
Due to the incorrect sizing of the iframe, horizontal scrollbar appears.

![image](https://github.com/heyxyz/hey/assets/88842947/b8a2c2f8-5245-42fd-a133-514cff11d0d7)

### Expected Behavior

The size of the `iframe` should be responsive, so that it does not overflows the viewport width as shown below.

![image](https://github.com/heyxyz/hey/assets/88842947/e6288a41-e7ec-48c4-8759-13caa33e00c7)

### Steps To Reproduce

- Go the website on a small screen device/smartphone.
- If there is an `iframe` anywhere in on the feed, the UI will break and you will see a horizontal scrollbar.

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome

### Anything else?

Width of the `iframe` should be adjusted.

**Comment by bigint** [comment] 2023-12-11 06:58
Dupe of #3949

**Closed by bigint** 2023-12-11 06:58 UTC
