### ISSUE TITLE
Some profile pictures are stretched

### ISSUE THREAD

**Issue by foolo** [heyxyz/hey#4012] opened 2023-11-16 15:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some profile picture are displayed stretched-out.

In this example, image is stretched out horizontally:

https://github.com/heyxyz/hey/assets/667227/66ce80d2-225d-40d7-95f6-1c9a5fe91c94

### Expected Behavior

The image should not be stretched or squeezed

### Steps To Reproduce

See https://hey.xyz/u/blaise

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by Dharmavineta** [comment] 2023-11-20 17:40
Hello, can I work on this Issue please? 
Also regarding the image, should I set it as object-cover or should i go with object-contain? Choosing object-cover will crop the image. Is that ok?
Will link a PR on moderator's suggestion.

**Comment by foolo** [comment] 2023-11-20 17:54
@Dharmavineta I'm not sure what the development status of the project is right now, (e.g. feature freeze or what issues are bountied/prioritized) so i guess it's a question for @bigint whether we want this now.

**Comment by bigint** [comment] 2023-11-30 11:07
Again this is issue with lens API, FYI: all images are handled on lens side 🙇🏼

**Comment by foolo** [comment] 2023-11-30 11:10
> Again this is issue with lens API, FYI: all images are handled on lens side 🙇🏼

This is a html/css issue. As you can see in the screenshot, the source image file is OK, but we render it stretched in the browser.

**Comment by Dharmavineta** [comment] 2023-11-30 12:16
All it needs is object-cover className for the profile image tag. Will link a PR if needed.

**Comment by bigint** [comment] 2023-12-13 05:15
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!

**Closed by bigint** 2023-12-13 05:15 UTC

**Comment by foolo** [comment] 2023-12-13 06:15
https://hey.xyz/u/ersankuneri

**Comment by bigint** [comment] 2023-12-13 06:45
The problem is lens didn't snapshot this image in imagekit, i raised internally to fix this on lens side!
